### ISSUE TITLE
Extend block fetching to work over the peer interface in addition to the RPC

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/btc-rpc-proxy#5]
Currently we only do dynamic block fetching for requests over the RPC interface. We should try and extend this to the peer interface as well.

**Comment by chrisguida** [comment]
Original purpose of this ticket was to support wallets that request blocks via the peer interface. Since dynamically fetching blocks in order to serve unauthenticated peers is a DoS vector and would probably never be a good idea, it seems unlikely that any pruned node implementation would ever implement this. Therefore it's up to the wallet developer to switch to using an rpc connection if they want to support pruned nodes.
